### ISSUE TITLE
Private methods and protected methods hooks are not intercepted

### ISSUE THREAD

**Issue by kraghuveer** [fstab/promagent#3]
Hi, I am trying to use promagent to collect some metrics, I was not able to intercept any private and protected methods with this library, could you please throw some light on this?

**Comment by fstab** [comment]
The current implementation instruments only public methods. From a quick look at the code it seems that it could be quite easy to support protected and private methods as well: Just remove the _isPublic()_ check in [io.promagent.internal.Promagent.matchAnyMethodIn() line 111](https://github.com/fstab/promagent/blob/a9e25911a70a17cd2c7ec6decf4702274a18a00c/promagent-framework/promagent-internal/src/main/java/io/promagent/internal/Promagent.java#L111). However, I didn't try it. I will get back to this as soon as I got the time to test it properly, but in the meantime you could just give it a try and comment out this line.

**Comment by kraghuveer** [comment]
Thanks a lot it worked.

**Comment by fstab** [comment]
Great. Removed the line from the code.
