### ISSUE TITLE
Classes that have static methods are not instrumented

### ISSUE THREAD

**Issue by kraghuveer** [fstab/promagent#5]
After specifying Hook method signatures, the classes that have static methods are not being instrumented. For example,  If I place any static method like below in a class file, the class is not being intercepted anymore,  I am not able to understand the reason behind this.
public static  void testinstrument(String str) {
        System.out.println("in test Instrument");
   }

**Comment by fstab** [comment]
Sorry for the late reply. It was a bug, I used the `this` pointer in `PromagentAdvice`, but obviously the `this` pointer is not available for static methods.

Fixed it, it should work now. Thanks for the bug report.
